### ISSUE TITLE
SO_Nutzungsplanung_20171118: duplicate version without precursor

### ISSUE THREAD

**Issue by edigonzales** [sogis/sogis-interlis-repository#2]
Warning: model SO_Nutzungsplanung_20171118: duplicate version without precursor; version 2017-11-18.1 ignored

**Comment by schmandr** [comment]
Habe die neuste Version 1.0.22 auch auf der Prod.-Umgebung deployt. Die Warnung kommt aber weiterhin. Vielleicht, weil ili2pg meinen lokalen Cache nicht aktualisiert und in meinem _~/.ilicache/geo.so.ch/models/ilimodels.xml_ weiterhin steht:

```
<IliRepository09.RepositoryIndex.ModelMetadata TID="65"><Name>SO_Nutzungsplanung_20171118</Name>
<SchemaLanguage>ili2_3</SchemaLanguage>
<File>ARP/replaced/SO_Nutzungsplanung_20171118.ili</File>
<Version>2017-11-18.1</Version>
...
```

**Comment by claeis** [comment]
Die Meldung weist auf eine Inkonsistenz im ilimodels.xml hin. Es gibt zwei oder mehrere Einträge mit dem selben Namen (SO_Nutzungsplanung_20171118) die alle  keinen Wert für ``<precursorVersion>`` haben. Aber alle, ausser einem (dem für das aktuelle Modell), müssen für precursorVersion einen Wert haben.

**Comment by edigonzales** [comment]
fixed
